### ISSUE TITLE
Ion torrent sequences

### ISSUE THREAD

**Issue by rentper93** [CVUA-RRW/FooDMe#62]
Hello, how are you?

I would like to know if I can use single-end sequences from Ion Torrent and, if so, what should I do?

Thank you very much.

**Comment by gregdenay** [comment]
Hi sorry for the late answer. At this time IonTorrent is not supported.
It would require some work to adapt the pre-processing steps to IonTorrent data but it should be possible.
I don't have the time required for this now, but if you feel like it's something you could tackle feel free to open a pull request and I will be happy to provide some help.

**Comment by gregdenay** [comment]
I am closing this issue now as it seems stall. Feel free to reopen if needed
